# Generated by Django 3.1.1 on 2020-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="amount_used",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The amount of times the subscription was used at deregistering of customers.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cancellation_number",
            field=models.CharField(
                blank=True,
                help_text="The cancellation number (possible paid).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_address",
            field=models.CharField(
                blank=True,
                help_text="The correspondence address of the subscription provider.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_city",
            field=models.CharField(
                blank=True,
                help_text="The city for the correspondence address of the subscription provider.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_postal_code",
            field=models.CharField(
                blank=True,
                help_text="The postal code for the correspondence address of the subscription provider.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                help_text="The name of the subscription.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The price per year for the subscription.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(
                help_text="The last part of the URL for the page of the subscription provider.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_city",
            field=models.CharField(
                blank=True,
                help_text="The city for the support reply number.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_email",
            field=models.EmailField(
                blank=True,
                help_text="The support email address for the subscription. If enabled in the website settings, this is also the email address where the deregister emails are sent to.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_phone_number",
            field=models.CharField(
                blank=True,
                help_text="The support phone number (not paid).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_postal_code",
            field=models.CharField(
                blank=True,
                help_text="The postal code for the support reply number.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_reply_number",
            field=models.CharField(
                blank=True,
                help_text="The reply number (Postbus) for the subscription provider (to send the customers letter to).",
                max_length=10,
                null=True,
            ),
        ),
    ]
