# Generated by Django 3.1.3 on 2020-11-15 14:29

from django.db import migrations, models
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20201026_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="email_template_text",
            field=models.FileField(
                blank=True,
                help_text="The template of the email to generate (as text). For more information about this please check the template help information.",
                null=True,
                upload_to=subscriptions.models.email_template_filename,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="letter_template",
            field=models.FileField(
                blank=True,
                help_text="The template of the letter to generate. For more information about this please check the template help information.",
                null=True,
                upload_to=subscriptions.models.letter_template_filename,
            ),
        ),
        migrations.AddField(
            model_name="subscriptioncategory",
            name="email_template_text",
            field=models.FileField(
                blank=True,
                help_text="The template of the email to generate (as text). For more information about this please check the template help information.",
                null=True,
                upload_to=subscriptions.models.email_template_filename,
            ),
        ),
        migrations.AddField(
            model_name="subscriptioncategory",
            name="letter_template",
            field=models.FileField(
                blank=True,
                help_text="The template of the letter to generate. For more information about this please check the template help information.",
                null=True,
                upload_to=subscriptions.models.letter_template_filename,
            ),
        ),
    ]
