# Generated by Django 3.0.4 on 2020-03-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20200316_0953"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SearchTerm", new_name="SubscriptionSearchTerm",
        ),
    ]
