# Generated by Django 3.0.4 on 2020-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200329_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancellation_number',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='support_phone_number',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
