# Generated by Django 3.1.3 on 2020-11-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_auto_20201115_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="cancellation_number",
            field=models.CharField(
                blank=True,
                help_text="The cancellation number (possibly paid).",
                max_length=1024,
                null=True,
            ),
        ),
    ]
