# Generated by Django 3.2 on 2021-05-05 18:48

from django.db import migrations
from django.conf import settings
import os
import shutil
from subscriptions.models import TEMPLATE_FILE_DIRECTORY


def move_media_folders(apps, schema_editor):
    """Move the media folders to a new directory (dependend upon the model name)."""
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionCategory = apps.get_model("subscriptions", "SubscriptionCategory")
    subscription_dir_from = os.path.join(
        os.path.join(settings.MEDIA_ROOT, "templates"), "subscription"
    )
    subscription_dir_to = os.path.join(
        os.path.join(settings.MEDIA_ROOT, TEMPLATE_FILE_DIRECTORY),
        Subscription._meta.model_name,
    )
    subscription_category_dir_from = os.path.join(
        os.path.join(settings.MEDIA_ROOT, "templates"), "subscription-category"
    )
    subscription_category_dir_to = os.path.join(
        os.path.join(settings.MEDIA_ROOT, TEMPLATE_FILE_DIRECTORY),
        SubscriptionCategory._meta.model_name,
    )
    if os.path.exists(subscription_dir_from) and not os.path.exists(
        subscription_dir_to
    ):
        shutil.move(subscription_dir_from, subscription_dir_to, False)
    if os.path.exists(subscription_category_dir_from) and not os.path.exists(
        subscription_category_dir_to
    ):
        shutil.move(subscription_category_dir_from, subscription_category_dir_to, False)


def change_db_file_locations(apps, schema_editor):
    """Change the db file path to the new path."""
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionCategory = apps.get_model("subscriptions", "SubscriptionCategory")
    for subscription in Subscription.objects.all():
        if subscription.letter_template:
            subscription.letter_template = (
                subscription.letter_template.__str__().replace(
                    "subscription", Subscription._meta.model_name, 1
                )
            )
        if subscription.email_template_text:
            subscription.email_template_text = (
                subscription.email_template_text.__str__().replace(
                    "subscription", Subscription._meta.model_name, 1
                )
            )
        if subscription.letter_template or subscription.email_template_text:
            subscription.save()

    for subscription_category in SubscriptionCategory.objects.all():
        if subscription_category.letter_template:
            subscription_category.letter_template = (
                subscription_category.letter_template.__str__().replace(
                    "subscription-category", SubscriptionCategory._meta.model_name, 1
                )
            )
        if subscription_category.email_template_text:
            subscription_category.email_template_text = (
                subscription_category.email_template_text.__str__().replace(
                    "subscription-category", SubscriptionCategory._meta.model_name, 1
                )
            )
        if (
            subscription_category.letter_template
            or subscription_category.email_template_text
        ):
            subscription_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_auto_20201116_1047"),
    ]

    operations = [
        migrations.RunPython(move_media_folders, migrations.RunPython.noop),
        migrations.RunPython(change_db_file_locations, migrations.RunPython.noop),
    ]
