# Generated by Django 3.0.7 on 2020-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_auto_20200611_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptioncategory",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
