# Generated by Django 3.0.7 on 2020-06-19 09:57

from django.db import migrations, models
from django.utils.text import slugify


def slugify_subscriptions(apps, schema_editor):
    """
    Slugify the subscriptions model.
    :param apps:
    :param schema_editor:
    :return:
    """
    Subscription = apps.get_model("subscriptions", "Subscription")
    for subscription in Subscription.objects.all():
        slug = slugify(subscription.name)
        if Subscription.objects.filter(slug=slug).exists():
            slug = "{}-{}".format(slug, subscription.id)
        subscription.slug = slug
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_auto_20200611_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.RunPython(slugify_subscriptions),
        migrations.AlterField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, null=False),
            preserve_default=False,
        ),
    ]
