# Generated by Django 3.0.7 on 2020-06-19 18:56

from django.db import migrations
from django.utils.text import slugify


def slugify_subscriptions(apps, schema_editor):
    """
    Slugify the subscriptions model.
    :param apps:
    :param schema_editor:
    :return:
    """
    Subscription = apps.get_model("subscriptions", "Subscription")
    for subscription in Subscription.objects.all():
        slug = slugify(subscription.name)
        if Subscription.objects.filter(slug=slug).exists():
            slug = "{}-{}".format(slug, subscription.id)
        subscription.slug = slug
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_auto_20200619_2054"),
    ]

    operations = [
        migrations.RunPython(slugify_subscriptions),
    ]
