# Generated by Django 3.0.7 on 2020-06-19 10:28

from django.db import migrations, models
from django.utils.text import slugify


def slugify_subscription_categories(apps, schema_editor):
    """
    Slugify the subscriptions model.
    :param apps:
    :param schema_editor:
    :return:
    """
    SubscriptionCategory = apps.get_model("subscriptions", "SubscriptionCategory")
    for category in SubscriptionCategory.objects.all():
        if category.slug is None or category.slug == "":
            slug = slugify(category.name)
            if SubscriptionCategory.objects.filter(slug=slug).exists():
                slug = "{}-{}".format(slug, category.id)
            category.slug = slug
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscription_slug"),
    ]

    operations = [
        migrations.RunPython(slugify_subscription_categories),
        migrations.AlterField(
            model_name="subscriptioncategory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
