# Generated by Django 3.2 on 2021-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_auto_20210716_1204"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedmaillist",
            name="address",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="queuedmaillist",
            name="email_address",
            field=models.EmailField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queuedmaillist",
            name="firstname",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queuedmaillist",
            name="lastname",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="queuedmaillist",
            name="postal_code",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="queuedmaillist",
            name="residence",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
