# Generated by Django 3.2 on 2021-07-24 15:40

from django.db import migrations, models


def move_user_information(apps, schema_editor):
    UserInformation = apps.get_model("users", "UserInformation")
    QueuedMailList = apps.get_model("subscriptions", "QueuedMailList")
    for queued_mail_list in QueuedMailList.objects.all():
        queued_mail_list.firstname = queued_mail_list.user_information.firstname
        queued_mail_list.lastname = queued_mail_list.user_information.lastname
        queued_mail_list.email_address = queued_mail_list.user_information.email_address
        queued_mail_list.address = queued_mail_list.user_information.address
        queued_mail_list.postal_code = queued_mail_list.user_information.postal_code
        queued_mail_list.residence = queued_mail_list.user_information.residence
        queued_mail_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_auto_20210724_1740"),
    ]

    operations = [
        migrations.RunPython(move_user_information, migrations.RunPython.noop),
        migrations.RemoveField(model_name="queuedmaillist", name="user_information"),
    ]
