# Generated by Django 3.0.7 on 2020-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_auto_20200619_2056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
