# Generated by Django 3.0.7 on 2020-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_auto_20200619_2057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioncategory",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
