# Generated by Django 3.2 on 2021-07-30 10:32

from django.db import migrations, models
import tinymce


def resave_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    for subscription in Subscription.objects.all():
        subscription.can_generate_letter = (
            bool(subscription.support_reply_number)
            and bool(subscription.support_postal_code)
            or bool(subscription.correspondence_address)
            and bool(subscription.correspondence_postal_code)
        )
        subscription.can_generate_email = bool(subscription.support_email)
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_auto_20210724_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="explanation_field",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text=(
                    "Possible explanation of how to deregister from this subscription if"
                    " deregistering via email or letter is not possible."
                ),
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="can_generate_email",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text=(
                    "Whether or not this subscription can generate a deregistration email."
                ),
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="can_generate_letter",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text=(
                    "Whether or not this subscription can generate a deregistration letter."
                ),
            ),
        ),
        migrations.RunPython(resave_subscriptions, migrations.RunPython.noop),
    ]
