# Generated by Django 3.2 on 2021-07-31 19:55

from django.db import migrations, models
from ordered_model.management.commands.reorder_model import Command


def reorder_subscription_category_model(apps, schema_editor):
    SubscriptionCategory = apps.get_model("subscriptions", "SubscriptionCategory")
    SubscriptionCategory.order_with_respect_to = "category"
    SubscriptionCategory.order_field_name = "order"
    command = Command()
    command.verbosity = True
    command.reorder(SubscriptionCategory)
    command.reorder_queryset(SubscriptionCategory.objects.filter(category=None))


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_auto_20210730_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioncategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            reorder_subscription_category_model, migrations.RunPython.noop
        ),
    ]
