# Generated by Django 3.2 on 2021-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_auto_20210730_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioncategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
