# Generated by Django 3.0.7 on 2020-06-19 19:04

from django.db import migrations
from django.utils.text import slugify


def slugify_subscription_categories(apps, schema_editor):
    """
    Slugify the subscriptions model.
    :param apps:
    :param schema_editor:
    :return:
    """
    SubscriptionCategory = apps.get_model("subscriptions", "SubscriptionCategory")
    for category in SubscriptionCategory.objects.all():
        category.slug = None
        category.save()
    for category in SubscriptionCategory.objects.all():
        slug = slugify(category.name)
        if SubscriptionCategory.objects.filter(slug=slug).exists():
            slug = "{}-{}".format(slug, category.id)
        category.slug = slug
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_auto_20200619_2101"),
    ]

    operations = [
        migrations.RunPython(slugify_subscription_categories),
    ]
