# Generated by Django 3.0.7 on 2020-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_auto_20200619_2104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioncategory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
