# Generated by Django 3.2.6 on 2021-08-04 11:44

from django.db import migrations, models


def set_fields_to_non_null(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    for subscription in Subscription.objects.all():
        if subscription.support_email is None:
            subscription.support_email = ""
        if subscription.support_reply_number is None:
            subscription.support_reply_number = ""
        if subscription.support_postal_code is None:
            subscription.support_postal_code = ""
        if subscription.support_city is None:
            subscription.support_city = ""
        if subscription.correspondence_address is None:
            subscription.correspondence_address = ""
        if subscription.correspondence_postal_code is None:
            subscription.correspondence_postal_code = ""
        if subscription.correspondence_city is None:
            subscription.correspondence_city = ""
        if subscription.support_phone_number is None:
            subscription.support_phone_number = ""
        if subscription.cancellation_number is None:
            subscription.cancellation_number = ""
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_subscriptioncategory_order"),
    ]

    operations = [
        migrations.RunPython(set_fields_to_non_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="queuedmaillist",
            name="address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="queuedmaillist",
            name="email_address",
            field=models.EmailField(max_length=512),
        ),
        migrations.AlterField(
            model_name="queuedmaillist",
            name="firstname",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="queuedmaillist",
            name="lastname",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="queuedmaillist",
            name="residence",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cancellation_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The cancellation number (possibly paid).",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The correspondence address of the subscription provider.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The city for the correspondence address of the subscription provider.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="correspondence_postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The postal code for the correspondence address of the subscription provider.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_city",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The city for the support reply number.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="The support email address for the subscription. If enabled in the website settings, this is also the email address where the deregister emails are sent to.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_phone_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The support phone number (not paid).",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The postal code for the support reply number.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="support_reply_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The reply number (Postbus) for the subscription provider (to send the customers letter to).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncategory",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="subscriptionsearchterm",
            name="name",
            field=models.CharField(max_length=512),
        ),
    ]
