# Generated by Django 3.0.7 on 2020-06-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20200619_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['name']},
        ),
    ]
