# Generated by Django 3.0.4 on 2020-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=256, unique=True)),
                ("email", models.EmailField(max_length=256, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=256)),
                ("lastname", models.CharField(blank=True, max_length=256)),
                ("email_address", models.EmailField(max_length=256)),
                ("address", models.CharField(blank=True, max_length=256)),
                ("postal_code", models.CharField(blank=True, max_length=6)),
                ("residence", models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
