# Generated by Django 3.0.7 on 2020-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200519_0834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="address",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="email_address",
            field=models.EmailField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="firstname",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="lastname",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="postal_code",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="residence",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
