# Generated by Django 3.2 on 2021-07-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_auto_20210724_1756"),
        ("users", "0004_auto_20200913_1432"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInformation",),
    ]
