# Generated by Django 3.2.6 on 2021-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_userinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailupdate",
            name="email_address",
            field=models.EmailField(max_length=512),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="profile",
            name="residence",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
