# Generated by Django 3.2.6 on 2021-08-04 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_userinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailupdate",
            name="email_address",
            field=models.EmailField(max_length=512),
        ),
        migrations.AlterField(
            model_name="emailupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="profile",
            name="residence",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
